version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@octokit/rest"
    versions:
    - 18.1.0
    - 18.2.0
    - 18.3.4
    - 18.5.2
  - dependency-name: minify
    versions:
    - 7.0.1
